//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDLL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"d:\\data\\Files\\Curtin\\Curtin " +
            "Year 4 Sem 2\\Distributed Computing\\DC_Assignment_1\\Chatbot_Assignment_1\\Chatbot_" +
            "Assignment_1\\ChatBot_Database.mdf\";Integrated Security=True")]
        public string ChatBot_DatabaseConnectionString {
            get {
                return ((string)(this["ChatBot_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"d:\\data\\Files\\Curtin\\Curtin " +
            "Year 4 Sem 2\\Distributed Computing\\DC_Assignment_1\\Chatbot_Assignment_1\\Chatbot_" +
            "Assignment_1\\ChatBot_Database.mdf\";Integrated Security=True")]
        public string ChatBot_DatabaseConnectionString1 {
            get {
                return ((string)(this["ChatBot_DatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\ChatBot_Datab" +
            "ase.mdf;Integrated Security=True")]
        public string ChatBot_DatabaseConnectionString2 {
            get {
                return ((string)(this["ChatBot_DatabaseConnectionString2"]));
            }
        }
    }
}
